### ISSUE TITLE
Push fail

### ISSUE THREAD

**Issue by suabbasi1** [vagabond-systems/forage-midas#1]
Push failed remote: Permission to vagabond-systems/forage-midas.git denied to suabbasi1. unable to access 'https://github.com/vagabond-systems/forage-midas.git/': The requested URL returned error: 403

**Comment by zjason25** [comment]
You're not supposed to push your changes to the main repository. You can fork a copy and push your changes there.

**Comment by Sibany007** [comment]
To fix the error mentioned in the GitHub issue, you can modify your `applications.yml` file as follows:

```yaml
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: localhost:9092
      group-id: your_group_id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    general:
      kafka-topic: your_topic_name
```
