### ISSUE TITLE
Had issue with Kafka producer when running test one

### ISSUE THREAD

**Issue by RBRNFRVR** [vagabond-systems/forage-midas#2]
had in issue with the bean running in test one, did some searching and found out that this specific error can be fixed by just adding
`general:
  kafka-topic: transaction-topic`

in the application.yml

Though not covered it could have been a mistake so to anyone that has the same issue after adding all the dependencies properly this is the fix that helped me. Also to any of the engineers who worked on this project(Yes Josiah I am talking about you) correct me if I am wrong if this wasn't the correct way to do it and there is a more proper way, first time working with spring boot so any advice would be very much appreciated. Also thank you to all the engineers that worked on this project its really fun.

Update: yeah the kafka topic in application.yml was accidently not added, in task two you discuss on how its already added but it seems the github it was missing or ignored, (didn't look into why) please update so no one else struggles like I did when the first task failed originally failed.

**Comment by edisonfreire** [comment]
I had this same issue in task 2, it seems that application.yml was empty from the beginning.

**Comment by saulyez** [comment]
applications.yml is empty when you fork it from the repo (I assume this must be an error). What helped me to get the tasks running is configuring the kafka producer and adding a Kafka-topic.

E.g
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
general:
  kafka-topic: your_topic_name

**Comment by sonderistic-boop** [comment]
In the second task however, the kafka topic is already meant to be defined. It's also empty in the original repository regardless

**Comment by JerioSoares60** [comment]
yes just add 
general.kafka-topic: transaction-topic
in the application.yml

**Comment by Sibany007** [comment]
```yaml
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    general:
      kafka-topic: your_topic_name
```
